name: CI

on:
  push:
    branches:
      - main

  pull_request_target:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.1

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2.0.1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Lint
        run: bun lint

      - name: Build
        run: bun run build

      - name: Check changeset
        run: bun run changeset:status
