name: Publish package

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}


jobs:
  release:
    permissions:
      # write permission is required to create a github release
      contents: write
      # write permission is required for autolabeler
      # otherwise, read permission is required at least
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.1
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4.0.4
        with:
          node-version: '20.x'

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2.0.1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Create Release Pull Request
        uses: changesets/action@v1
        with:
          version: bun run ci:version
          commit: 'chore: update versions'
          publish: bun run ci:publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
